In [12]:
from magilearn.metrics import accuracy_score

y_true = [1, 0, 1, 1, 0]  # 真实标签
y_pred = [1, 0, 1, 0, 0]  # 预测标签

accuracy = accuracy_score(y_true, y_pred)
print("准确率:", accuracy)

准确率: 0.8


In [3]:
from magilearn.metrics import confusion_matrix

y_true = [1, 0, 1, 1, 0]
y_pred = [1, 0, 1, 0, 0]

matrix = confusion_matrix(y_true, y_pred)
print("混淆矩阵:\n", matrix)

混淆矩阵:
 [[2 0]
 [1 2]]


In [1]:
from magilearn.metrics import precision_score, recall_score

y_true = [1, 0, 1, 1, 0]
y_pred = [1, 0, 1, 0, 0]

precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
print("精确率:", precision)
print("召回率:", recall)

精确率: 1.0
召回率: 0.6666666666666666


In [1]:
from magilearn.metrics import roc_auc_score

y_true = [1, 0, 1, 1, 0]
y_scores = [0.8, 0.4, 0.9, 0.6, 0.3]  # 预测分数或概率

auc = roc_auc_score(y_true, y_scores)
print("ROC AUC:", auc)

ROC AUC: 1.0


In [3]:
from magilearn.preprocessing import StandardScaler
import numpy as np

X = np.array([[1, 2], [2, 3], [3, 4]])  # 示例数据

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("标准化数据:\n", X_scaled)

标准化数据:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [4]:
from magilearn.preprocessing import MinMaxScaler
import numpy as np

X = np.array([[1, 2], [2, 3], [3, 4]])  # 示例数据

scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)
print("归一化数据:\n", X_normalized)

归一化数据:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [5]:
from magilearn.preprocessing import OneHotEncoder
import numpy as np

X = np.array([["apple"], ["banana"], ["apple"], ["orange"]])  # 示例数据

encoder = OneHotEncoder()
X_encoded = encoder.fit_transform(X)
print("One-Hot 编码:\n", X_encoded)

One-Hot 编码:
 [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [8]:
from magilearn.preprocessing import LabelEncoder
import numpy as np

y = np.array(["cat", "dog", "fish", "monkey", "tiger"])  # 示例标签

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
print("标签编码:", y_encoded)

标签编码: [0 1 2 3 4]
